import {
  CalendarClock,
  CalendarDays,
  ChartColumn,
  ChefHat,
  CircleDollarSign,
  ClipboardCheck,
  CreditCard,
  Download,
  Hourglass,
  Home,
  LayoutGrid,
  ListPlus,
  Megaphone,
  NotebookText,
  Package,
  PackagePlus,
  ScanLine,
  Settings,
  ShoppingBag,
  Star,
  Tablet,
  Ticket,
  Truck,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "../_lib/navigation-presentation";

const ICONS: Record<IconKey, LucideIcon> = {
  home: Home,
  calendar: CalendarDays,
  ticket: Ticket,
  scan: ScanLine,
  megaphone: Megaphone,
  reservation: CalendarClock,
  waitlist: Hourglass,
  guests: ClipboardCheck,
  star: Star,
  tables: LayoutGrid,
  orders: ChefHat,
  cash: Wallet,
  card: CreditCard,
  menu: NotebookText,
  product: ShoppingBag,
  modifier: ListPlus,
  inventory: Package,
  purchase: PackagePlus,
  supplier: Truck,
  dollar: CircleDollarSign,
  chart: ChartColumn,
  export: Download,
  users: Users,
  settings: Settings,
  tablet: Tablet,
};

export function UnifiedNavIcon({ iconKey, size = 16, className }: { iconKey: IconKey; size?: number; className?: string }) {
  const Icon = ICONS[iconKey];
  return <Icon size={size} className={className} />;
}
